<?php
return array (
  2 => 
  array (
    'posid' => '2',
    'modelid' => '3',
    'catid' => '29',
    'name' => '住宅装修案例推荐',
    'maxnum' => '1',
    'extention' => '',
    'listorder' => '4',
    'siteid' => '1',
    'thumb' => '',
  ),
  17 => 
  array (
    'posid' => '17',
    'modelid' => '3',
    'catid' => '29',
    'name' => '别墅装修案例推荐',
    'maxnum' => '1',
    'extention' => '',
    'listorder' => '3',
    'siteid' => '1',
    'thumb' => '',
  ),
  1 => 
  array (
    'posid' => '1',
    'modelid' => '3',
    'catid' => '29',
    'name' => '酒店装修案例推荐',
    'maxnum' => '1',
    'extention' => '',
    'listorder' => '2',
    'siteid' => '1',
    'thumb' => '',
  ),
  16 => 
  array (
    'posid' => '16',
    'modelid' => '3',
    'catid' => '29',
    'name' => '办公装修案例推荐',
    'maxnum' => '1',
    'extention' => '',
    'listorder' => '1',
    'siteid' => '1',
    'thumb' => '',
  ),
  18 => 
  array (
    'posid' => '18',
    'modelid' => '12',
    'catid' => '17',
    'name' => '工艺保障推荐',
    'maxnum' => '1',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  20 => 
  array (
    'posid' => '20',
    'modelid' => '12',
    'catid' => '19',
    'name' => '管理保障推荐',
    'maxnum' => '1',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  15 => 
  array (
    'posid' => '15',
    'modelid' => '3',
    'catid' => '29',
    'name' => '经典案例推荐',
    'maxnum' => '7',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  19 => 
  array (
    'posid' => '19',
    'modelid' => '12',
    'catid' => '18',
    'name' => '质量保障推荐',
    'maxnum' => '1',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  10 => 
  array (
    'posid' => '10',
    'modelid' => '15',
    'catid' => '0',
    'name' => '活动推荐',
    'maxnum' => '1',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  9 => 
  array (
    'posid' => '9',
    'modelid' => '1',
    'catid' => '15',
    'name' => '客户心声图片推荐',
    'maxnum' => '2',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  8 => 
  array (
    'posid' => '8',
    'modelid' => '1',
    'catid' => '16',
    'name' => '新闻动态图片推荐',
    'maxnum' => '3',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  21 => 
  array (
    'posid' => '21',
    'modelid' => '12',
    'catid' => '20',
    'name' => '验收保障推荐',
    'maxnum' => '1',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  22 => 
  array (
    'posid' => '22',
    'modelid' => '2',
    'catid' => '0',
    'name' => '首页团队推荐',
    'maxnum' => '24',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
);
?>